### ISSUE TITLE
[HDrenderloop]Major memory leak on OSX metal

### ISSUE THREAD

**Issue by Verasl** [Unity-Technologies/ScriptableRenderLoop#106]
Currently, having the HDrenderloop set in graphics settings on OSX, running Metal editor causes unity to leak huge amounts of memory, easily getting to 60GBs+ within a minute or two.

It only happens when a scene or game view is visible, switching to asset store or similar to hide any 3d viewport stops the leak, as soon as you return to one it start going up again.

I have tried both the base scriptable-renderloop and scriptable-renderloop/metal branches and the outcome is the same.

FPTL and basic loops(pipelines :)) are fine.

**Comment by aet** [comment]
can't repro against latest (unreleased beta) stuff :) closing
