### ISSUE TITLE
Is it really happening?

### ISSUE THREAD

**Issue by bitfabrikken** [Unity-Technologies/ScriptableRenderLoop#221]
If this is indeed coming in Unity, I will just about explode from happiness. There's thousands of us waiting for this!

Could this possibly allow running graphics at 15fps, while still maintaining 60 fps input on mobile platforms? If yes, it's going to be absolutely huge!

(Sorry for this not actually being an issue, but rather a comment / encouragement to whoever is working on it)

Got here from this:
https://feedback.unity3d.com/suggestions/realtime-input-framerate-indepe
https://feedback.unity3d.com/suggestions/manually-activated-render-loop-for-lower-power-consumption-on-mobile

**Comment by sebastienlagarde** [comment]
Hi, 
Thanks for your enthusiasm.
The SRP project is only about flexible renderpipeline, it will not allow to manipulate input loop delta time. So no way to decouple input reading and graphic rendering frame rate, sorry.

**Comment by Rene-Damm** [comment]
@bitfabrikken On a semi-related note, the new input system is moving event collection to threads where it makes sense. This allows sampling things like touch on a higher-than-framerate frequency, for example. So in that sense, you could run your game at 15fps while sampling input at 60fps.

**Comment by bitfabrikken** [comment]
@Rene-Damm thanks Rene :) Do you know if there's a github repo I can follow for that input system?

**Comment by Rene-Damm** [comment]
@bitfabrikken We're getting there :) We've hit delays and snags but we're making steady progress towards that stage. There should be a publicly accessible github version in the 2017.1 time frame and a fully integrated version in 2017.2 (we're moving towards Unity being able to integrate packages from the web).
