### ISSUE TITLE
Extrimply need this fiture!

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/ScriptableRenderLoop#32]
Hi, i research sources, And this is awesome! It will be help change render logic, add some features!

I thing RenderLoop not necessary class, may use only CommandBuffer

CommandBuffer buff;
FillCommandBuffer(buff);
buff.ExecuteOnGPU(); 

Awesome, thanks, will wait it in unity!!!

**Comment by aras-p** [comment]
Not sure I understood the request frankly. What ExecuteOnGPU would end up doing, and where?

**Comment by fdsagizi** [comment]
i just want say, this is really cool thin!!! :)

About command buffer,i mean it can be like this

1 create command buffer
2 fill command buffer
3 execute it

 without RenderLoop ;)

**Comment by aras-p** [comment]
You can do this today in any unity 5.0+ version; create a command buffer, fill it, and do Graphics.ExecuteCommandBuffer.
