### ISSUE TITLE
what Unity version should I use?

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderLoop#320]
Hi,
I tried opening this with the latest beta (2017.1.0b7) but the project version says 2017.2.0b1... I'm on the alpha list but the latest version there is 2017.2.0a4.
So I tried checking out the tag unity-2017.1b5, but after reimport I see most of the shaders have been auto-upgraded (replaced 'mul(UNITY_MATRIX_MVP,*)' with 'UnityObjectToClipPos(*)').
Does it matter at all? Which version should I use?

**Comment by sebastienlagarde** [comment]
Hey, 
We regularly update the Unity C++ code for this project, mean latest github version is high likely to not work on latest public available Unity version (alpha, beta, priority list). It is highly develop and highly experimental feature.

The only release that currently work is with Unity 2017.1b5 build:
https://github.com/Unity-Technologies/ScriptableRenderLoop/releases/tag/unity-2017.1b5

>but after reimport I see most of the shaders have been auto-upgraded (replaced >'mul(UNITY_MATRIX_MVP,)' with 'UnityObjectToClipPos()').
There is no use of  UNITY_MATRIX_MVP in this github project, so it shouldn't matter.

Hope it help.

**Comment by benblo** [comment]
OK so basically latest is for UT internal use only right?

I started looking at the 2017.1 tag which mostly works, except some of the (older?) test scenes like Big (viking village) and FPTL are broken: had to rebuild outdated lighting data, but even after that it's all black.
I'm quite interested in FPTL, any idea what needs to be fixed?

**Comment by benblo** [comment]
OK got it, had to assign the FPTL asset in the graphics settings.
I suppose this can be done procedurally... this demo project would be a bit friendlier if the proper pipeline was selected when opening scenes ;).

**Comment by sebastienlagarde** [comment]
Yes, there is no automatic detection of which pipeline asset to use as it is not really possible to know (you can have several fork of the same render pipe with very slight variation.

Note: FTPL is a toy project that we use to experiment/implement tile/cluster lighting, there is currently no plan to ship it and we will remove it in the future. But feel free to use it for your own need :)

**Comment by benblo** [comment]
Thanks. I don't plan to _use_ FPTL, I'm merely dissecting it to figure out how it's implemented... so far, it's a toughie ;) !

**Comment by sebastienlagarde** [comment]
You can find the details in GPU Pro 7 article from Morten Mikkelsen, it is an improve version of the article (done by the author himself as he work at Unity).
