### ISSUE TITLE
global shader variables

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderLoop#385]
So... 1 question and 1 request:
* What's the status of RenderSettings and SRP? Are ambient color fog settings etc still set? I have a weird bug where ambient light color is not the same when I enable SRP. It's also not the same in game and scene view!
  * BTW, I see that the UNITY_LIGHTMODEL_AMBIENT macro returns glstate_lightmodel_ambient... why is ambient a glstate and not just a global constant? Feels like a leftover of fixed function pipeline...?
* When are global constants set? **Can we set them ourselves?** In the interest of full scriptableness, it would seem fit that we can set everything ourselves, with obviously easy defaults:
```
	renderContext.SetDefaultGlobals();
```
but we could also do:
```
	var globalCmd = new CommandBuffer();
	globalCmd.name = "custom globals";
	globalCmd.SetGlobalFloat("_Time", Time.time);
	globalCmd.SetGlobalColor("unity_AmbientSky", Color.magenta);
	...
	renderContext.ExecuteCommandBuffer(globalCmd);
	globalCmd.Release();
```

**Comment by benblo** [comment]
Regarding the ambient light setting: I'm pretty sure SRP doesn't set it, whatever value is in there seems to be what was left by whoever modified it last, the scene view seeming a likely culprit (it sets its own ambient light if the "light" toggle is off, instead of using the scene settings).

Also, it seems like Pipeline.Render() is called twice per frame (at least in edit mode*), and I receive different values one in two times: first time the scene ambient, second time the scene view custom ambient.

(*) BTW it's hard to figure out the frame number when in edit-mode: in legacy, Time.frameCount seems to increase at the editor update rate (100hz), so in my case 30 frames pass in between 2 renders. In SRP, frameCount only increment by 1 every 2 Render() calls...

BTW I'm on 2017.1 f3.

**Comment by sebastienlagarde** [comment]
> Are ambient color fog settings etc still set?
Not sure about this one, I need to ask around. 

SRP don't have feature parity with legacy Unity, mean all features are not fully supported. 
Something like the fog tend to be re-do differently by the various render pipeline (for example, HD Pipe use a different system), thus why this may not have been supported. In the mean time, it still possible to provide your own fog system.

>UNITY_LIGHTMODEL_AMBIENT macro returns glstate_lightmodel_ambient... why is ambient a glstate and not just a global constant?

No idea, Unity is full of legacy stuff. Better to ask on unity forum.

>When are global constants set? Can we set them ourselves? 

Global constant are set by the C++/engine and thus are not controllable. This is due to legacy as not SRP render pipeline must continue to work.

We have no plan currently to expose setup of these global constants via C#.

For Frame/Scene/Camera frequency variable to be fully scriptable, you will require to write your own shader with your own variable and your own setup of constant (this is what is done in HD Render Pipeline). The constant at object frequency (lightprobe/lightmap...) are always provided by the C++ as there is no object-level access in C#.

>Pipeline.Render() is called twice per frame (at least in edit mode*)

It is call several time per frame (multiple view call Render() like the preview, sceneview etc...). Use Time.frameCount to know the current frame.

**Comment by benblo** [comment]
> Are ambient color fog settings etc still set?
> Not sure about this one, I need to ask around.
> SRP don't have feature parity with legacy Unity, mean all features are not fully supported.
> Something like the fog tend to be re-do differently by the various render pipeline (for example, HD Pipe use a different system), thus why this may not have been supported. In the mean time, it still possible to provide your own fog system.
> 
In my case doing this was enough to fix the issue:
```
	cmd.SetGlobalColor("glstate_lightmodel_ambient", RenderSettings.ambientLight / 2); // divide by 2 because UNITY_LIGHTMODEL_AMBIENT macro multiplies by 2... yay

```
... but sure, I think we'll just ditch any builtin variable use and just provide our own, it's more explicit this way.

---
> When are global constants set? Can we set them ourselves?
> Global constant are set by the C++/engine and thus are not controllable. This is due to legacy as not SRP render pipeline must continue to work.
> 
> We have no plan currently to expose setup of these global constants via C#.
> 
OK... but I mean, if at least you can guarantee that the C++ variables are set before any of our scriptable commands run, then we should be able to simply override any global we want using a CommandBuffer at the beginning of the each frame, right?

---
> For Frame/Scene/Camera frequency variable to be fully scriptable, you will require to write your own shader with your own variable and your own setup of constant (this is what is done in HD Render Pipeline). The constant at object frequency (lightprobe/lightmap...) are always provided by the C++ as there is no object-level access in C#.
> 
Yes, no per-object variables... I have a feeling you won't get away with this for long though ;) ! Sooner or later we'll need to be able to write our own custom renderers with their own sets of variables, it just feels sort of inevitable if you want true extensibility.
Probably a topic for another day though ;) !

 ---
> Pipeline.Render() is called twice per frame (at least in edit mode*)
> It is call several time per frame (multiple view call Render() like the preview, sceneview etc...). Use Time.frameCount to know the current frame.
> 
Uh. So does that mean that Render() is called once for all SceneViews, once for GameView with all user cameras, etc? I always assumed the array contained ALL the cameras... I'll have to check more carefully.

**Comment by sebastienlagarde** [comment]
> if at least you can guarantee that the C++ variables are set before any of our scriptable commands run, >then we should be able to simply override any global we want using a CommandBuffer at the beginning >of the each frame, right?

It is the case already. If a value is not set, it mean that we forgot to set it for SRP, it will not be set later (or maybe a legacy code will set it somewhere for unclear reasons

> it just feels sort of inevitable if you want true extensibility.
It is required to not have access to objects if you want performance :). C# is still slow like hell.

>Uh. So does that mean that Render() is called once for all SceneViews, once for GameView with all user >cameras, etc? I always assumed the array contained ALL the cameras..

yes, that is a confusing behavior, but due to how Unity editor work.

**Comment by benblo** [comment]
> if at least you can guarantee that the C++ variables are set before any of our scriptable commands run, >then we should be able to simply override any global we want using a CommandBuffer at the beginning >of the each frame, right?
> It is the case already. If a value is not set, it mean that we forgot to set it for SRP, it will not be set later (or maybe a legacy code will set it somewhere for unclear reasons
> 
Great, thanks!

> it just feels sort of inevitable if you want true extensibility.
> It is required to not have access to objects if you want performance :). C# is still slow like hell.
> 
Eheh, for sure! I was thinking of the far future ;)
That really feels like a perfect fit for the job system: define custom renderers, with the corresponding rendererSystem, that would process the culled objects in cache coherent batches, etc.
... or, allow us to write C++ renderers... in a much further future!

> Uh. So does that mean that Render() is called once for all SceneViews, once for GameView with all user >cameras, etc? I always assumed the array contained ALL the cameras..
> yes, that is a confusing behavior, but due to how Unity editor work.
>
Actually after thinking about it, it probably makes sense: the editor may want to redraw the scene view but not the game view, or vice versa.

Anyway, thanks a lot!
