### ISSUE TITLE
ability to disable/change pipeline in a build

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderLoop#388]
I'm porting a project to SRP, going slow but steady so far.
I'd like to be able to toggle between legacy and SRP in a build, so I view any differences, compare framerate, etc... didn't find a way to do this via API, only Graphics Settings: am I missing something?

**Comment by sebastienlagarde** [comment]
>I'd like to be able to toggle between legacy and SRP in a build
You can do this with GraphicsSettings.renderPipelineAsset changing it will switch the render pipeline. settings null will enable legacy. 

Note: This is fine for a render pipeline base on legacy shader, but some render pipeline don't support legacy pipeline at all like HD.

**Comment by benblo** [comment]
> You can do this with GraphicsSettings.renderPipelineAsset changing it will switch the render pipeline. settings null will enable legacy.
> 
Awesome, got my build! can't believe I missed that.

> Note: This is fine for a render pipeline base on legacy shader, but some render pipeline don't support legacy pipeline at all like HD.
>
Yup that's understood, but it's fine in our case.

Thanks for all your answers Seb :) !
